import { createFileRoute, Link } from "@tanstack/react-router";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";

export const Route = createFileRoute("/blog/pixel-art-history")({
  head: () => ({
    meta: [
      { title: "A Brief History of Pixel Art | PixelCanvas Blog" },
      { name: "description", content: "Pixel art started as a technical constraint and became a celebrated art form. Trace its evolution from early video games to modern design." },
    ],
  }),
  component: Page,
});

function Page() {
  return (
    <div className="min-h-screen bg-paper text-ink">
      <Nav />
      <main className="mx-auto max-w-3xl px-4 py-10 prose prose-sm max-w-none">
        <Link to="/blog" className="text-sm text-flame hover:underline">← Back to Blog</Link>
        <h1 className="font-display text-4xl mt-4 mb-2">A Brief History of Pixel Art: From 8-Bit to Modern Masterpieces</h1>
        <p className="text-sm text-muted-foreground mb-8">June 2026 · 5 min read</p>

        <p>Pixel art began not as an aesthetic choice but as a technical necessity. In the 1970s and 80s, the limited memory and processing power of early computers and game consoles meant that graphics had to be small, simple, and carefully constructed one pixel at a time. What started as constraint became craft — and eventually, a celebrated art form in its own right.</p>

        <h2>The Technical Origins</h2>
        <p>The earliest digital graphics were created on machines with severe limitations. The Atari 2600, released in 1977, had a display resolution of 160×192 pixels with a limited color palette. Every pixel had to be intentional. Artists working on these platforms developed extraordinary skill at communicating form, movement, and emotion through tiny grids of color.</p>
        <p>The Famicom (NES) era of the 1980s pushed pixel art to its cultural peak. Games like Super Mario Bros., The Legend of Zelda, and Mega Man defined visual languages that billions of people still recognize instantly. Sprites were typically 16×16 or 32×32 pixels. The constraint forced clarity — every pixel had a purpose.</p>

        <h2>The 16-Bit Renaissance</h2>
        <p>The Super Nintendo and Sega Genesis era brought more colors, larger sprites, and more sophisticated techniques. Artists developed methods like dithering (alternating pixels of two colors to simulate a third), careful highlight and shadow placement, and consistent perspective rules. Chrono Trigger, Street Fighter II, and Final Fantasy VI represent the artistic pinnacle of hardware-constrained pixel art.</p>

        <h2>When Pixel Art Became Optional</h2>
        <p>By the mid-1990s, hardware had advanced enough that 3D graphics became viable. Pixel art stopped being necessary. For a decade or so, it was associated with low budgets and outdated technology. Then something interesting happened: it came back, deliberately.</p>
        <p>Indie developers in the mid-2000s began choosing pixel art not because they had to, but because they wanted to. Cave Story (2004), created by a single developer over five years, demonstrated that pixel art could carry an emotionally rich, full-length game. It proved pixel art was an aesthetic choice, not a compromise.</p>

        <h2>Pixel Art Today</h2>
        <p>In 2026, pixel art is everywhere. It appears in critically acclaimed games, graphic novels, product design, and fashion. Artists like Paul Robertson create detailed, animated pixel scenes that function as standalone artworks. The format has its own conventions, communities, and tools — Aseprite has become the industry-standard pixel art editor with tens of thousands of active users.</p>
        <p>What makes pixel art endure is its legibility. Every shape is simplified to its essence. Every color choice is visible and deliberate. At a time when most digital imagery is generated by algorithms or captured by cameras, pixel art is unmistakably hand-crafted — individual decisions visible in every square.</p>

        <div className="brut-border bg-zap/30 p-5 mt-8 not-prose">
          <p className="font-bold mb-1">Add your pixel to the canvas</p>
          <p className="text-sm text-muted-foreground mb-3">One square. Your color. Your link. Forever.</p>
          <Link to="/canvas" className="inline-block brut-border bg-flame px-4 py-2 font-display text-sm uppercase text-paper brut-shadow-sm">Open the canvas →</Link>
        </div>
      </main>
      <Footer />
    </div>
  );
}
